import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import KnowledgeArticleCard from "@/components/KnowledgeArticleCard";
import KnowledgeVisual from "@/components/KnowledgeVisual";
import { getKnowledgeArticle, getKnowledgeTopic, knowledgeArticles, knowledgeVisualImages } from "@/data/knowledge";
import { productCategories } from "@/data/products";
import { categoryPath, getAbsoluteImage, getAbsoluteUrl } from "@/lib/product-seo";
import { isLocale, localizedPath, type Locale } from "@/lib/i18n";

type Props = { params: Promise<{ lang: string; topic: string; slug: string }> };
export function generateStaticParams() { return ["en", "zh"].flatMap((lang) => knowledgeArticles.map((article) => ({ lang, topic: article.topic, slug: article.slug }))); }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { lang: value, topic, slug } = await params; if (!isLocale(value)) return {}; const lang = value as Locale; const article = getKnowledgeArticle(topic, slug); if (!article) return {};
  const path = `/knowledge/${topic}/${slug}`;
  const image = knowledgeVisualImages[article.visual];
  return { title: article.title[lang], description: article.description[lang], keywords: article.keywords[lang], alternates: { canonical: localizedPath(lang, path), languages: { "en-US": localizedPath("en", path), "zh-CN": localizedPath("zh", path), "x-default": localizedPath("en", path) } }, openGraph: { type: "article", title: article.title[lang], description: article.description[lang], url: localizedPath(lang, path), publishedTime: article.published, modifiedTime: article.modified, authors: [lang === "zh" ? "赣星表面处理技术团队" : "GANXING Surface Finishing Technical Team"], images: [{ url: image, alt: article.title[lang] }] }, twitter: { card: "summary_large_image", title: article.title[lang], description: article.description[lang], images: [image] } };
}

export default async function ArticlePage({ params }: Props) {
  const { lang: value, topic, slug } = await params; if (!isLocale(value)) notFound(); const lang = value as Locale; const article = getKnowledgeArticle(topic, slug); const topicData = getKnowledgeTopic(topic); if (!article || !topicData) notFound();
  const path = localizedPath(lang, `/knowledge/${topic}/${slug}`); const author = lang === "zh" ? "赣星表面处理技术团队" : "GANXING Surface Finishing Technical Team";
  const jsonLd = { "@context": "https://schema.org", "@graph": [{ "@type": "Article", headline: article.title[lang], description: article.description[lang], image: getAbsoluteImage(knowledgeVisualImages[article.visual]), datePublished: article.published, dateModified: article.modified, inLanguage: lang === "zh" ? "zh-CN" : "en-US", mainEntityOfPage: getAbsoluteUrl(path), author: { "@type": "Organization", name: author }, publisher: { "@type": "Organization", name: lang === "zh" ? "赣星电动工具" : "GANXING Tools", logo: { "@type": "ImageObject", url: getAbsoluteUrl("/images/brand/ganxing-logo.png") } }, about: topicData.title[lang], keywords: article.keywords[lang].join(", ") }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: lang === "zh" ? "首页" : "Home", item: getAbsoluteUrl(localizedPath(lang)) }, { "@type": "ListItem", position: 2, name: lang === "zh" ? "知识中心" : "Knowledge Center", item: getAbsoluteUrl(localizedPath(lang, "/knowledge")) }, { "@type": "ListItem", position: 3, name: topicData.shortTitle[lang], item: getAbsoluteUrl(localizedPath(lang, `/knowledge/${topic}`)) }, { "@type": "ListItem", position: 4, name: article.title[lang], item: getAbsoluteUrl(path) }] }] };
  const categories = article.relatedCategorySlugs.map((categorySlug) => productCategories.find((category) => category.slug === categorySlug)).filter(Boolean) as typeof productCategories;
  const sameTopic = knowledgeArticles.filter((item) => item.topic === article.topic && item.slug !== article.slug);
  const related = (sameTopic.length ? sameTopic : knowledgeArticles.filter((item) => item.slug !== article.slug)).slice(0, 2);

  return <main className="min-h-screen bg-[#f5f5f2] pt-14 sm:pt-16"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
    <article>
      <header className="border-b border-neutral-200 bg-white px-4 py-14 sm:px-5 sm:py-20 lg:px-8"><div className="mx-auto max-w-5xl"><nav aria-label="Breadcrumb" className="flex flex-wrap gap-2 text-sm text-neutral-500"><Link href={localizedPath(lang, "/knowledge")} className="hover:text-red-600">{lang === "zh" ? "知识中心" : "Knowledge"}</Link><span>/</span><Link href={localizedPath(lang, `/knowledge/${topic}`)} className="hover:text-red-600">{topicData.shortTitle[lang]}</Link></nav><p className="mt-10 text-xs font-bold uppercase tracking-[0.24em] text-red-600">{lang === "zh" ? "赣星技术指南" : "GANXING Technical Guide"}</p><h1 className="mt-5 text-4xl font-black leading-[1.08] tracking-[-0.04em] text-neutral-950 sm:text-6xl">{article.title[lang]}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-neutral-600">{article.description[lang]}</p><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-neutral-500"><span>{author}</span><span>{article.readingTime[lang]}</span><time dateTime={article.modified}>{lang === "zh" ? "更新于" : "Updated"} {article.modified}</time></div></div></header>

      <div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-5 lg:grid-cols-[230px_minmax(0,800px)] lg:justify-center lg:px-8 lg:py-16">
        <aside className="hidden lg:block"><div className="sticky top-24"><p className="text-xs font-bold uppercase tracking-[.2em] text-neutral-400">{lang === "zh" ? "本页内容" : "On this page"}</p><nav className="mt-4 border-l border-neutral-300">{article.sections.map((section) => <a key={section.id} href={`#${section.id}`} className="block border-l-2 border-transparent px-4 py-2 text-sm leading-5 text-neutral-600 transition hover:border-red-600 hover:text-red-700">{section.title[lang]}</a>)}</nav></div></aside>
        <div className="min-w-0">
          <section aria-labelledby="quick-answer" className="rounded-[2rem] border border-red-200 bg-red-50 p-6 sm:p-8"><p id="quick-answer" className="text-xs font-black uppercase tracking-[.22em] text-red-700">{lang === "zh" ? "快速结论" : "Quick answer"}</p><p className="mt-4 text-lg font-semibold leading-8 text-neutral-900">{article.quickAnswer[lang]}</p></section>
          <div className="mt-12 space-y-16">{article.sections.map((section) => <section key={section.id} id={section.id} className="scroll-mt-24"><h2 className="text-3xl font-black tracking-tight text-neutral-950 sm:text-4xl">{section.title[lang]}</h2>{section.paragraphs?.map((paragraph, i) => <p key={i} className="mt-5 text-base leading-8 text-neutral-700 sm:text-lg">{paragraph[lang]}</p>)}{section.visual && <div className="mt-8"><KnowledgeVisual type={section.visual} lang={lang} /></div>}{section.steps && <ol className="mt-8 space-y-4">{section.steps.map((step, i) => <li key={step.title.en} className="grid gap-4 rounded-3xl border border-neutral-200 bg-white p-5 sm:grid-cols-[52px_1fr] sm:p-6"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-neutral-950 text-sm font-black text-white">{String(i + 1).padStart(2,"0")}</span><div><h3 className="text-lg font-bold text-neutral-950">{step.title[lang]}</h3><p className="mt-2 leading-7 text-neutral-600">{step.body[lang]}</p></div></li>)}</ol>}{section.bullets && <ul className="mt-7 space-y-3">{section.bullets.map((bullet) => <li key={bullet.en} className="flex gap-3 leading-7 text-neutral-700"><span className="mt-2.5 h-2 w-2 shrink-0 rounded-full bg-red-600" />{bullet[lang]}</li>)}</ul>}{section.table && <div className="mt-8 overflow-x-auto rounded-2xl border border-neutral-200 bg-white"><table className="w-full min-w-[680px] border-collapse text-left"><thead className="bg-neutral-950 text-white"><tr>{section.table.headers.map((header) => <th key={header.en} className="px-5 py-4 text-sm font-bold">{header[lang]}</th>)}</tr></thead><tbody>{section.table.rows.map((row, rowIndex) => <tr key={rowIndex} className="border-t border-neutral-200">{row.map((cell, cellIndex) => <td key={cellIndex} className="px-5 py-4 align-top text-sm leading-6 text-neutral-700">{cell[lang]}</td>)}</tr>)}</tbody></table></div>}{section.callout && <div className={`mt-7 rounded-2xl border-l-4 p-5 ${section.callout.tone === "warning" ? "border-amber-500 bg-amber-50" : "border-red-600 bg-white"}`}><h3 className="font-bold text-neutral-950">{section.callout.title[lang]}</h3><p className="mt-2 leading-7 text-neutral-700">{section.callout.body[lang]}</p></div>}</section>)}</div>

          <section className="mt-16 border-t border-neutral-300 pt-10"><p className="text-sm leading-6 text-neutral-500">{lang === "zh" ? "安全提示：本指南用于建立判断框架，不能替代对具体表面、涂层厚度、材料兼容性和机器说明书的现场评估。请先做小面积测试并佩戴适用的个人防护用品。" : "Safety note: This guide provides a decision framework and does not replace an on-site assessment of the surface, coating thickness, material compatibility, or the machine manual. Test a small area first and use appropriate PPE."}</p></section>
        </div>
      </div>
    </article>

    <section className="border-y border-neutral-200 bg-white px-4 py-16 sm:px-5 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-red-600">{lang === "zh" ? "相关工具系统" : "Related tool systems"}</p><h2 className="mt-4 text-3xl font-black text-neutral-950">{lang === "zh" ? "把知识应用到正确设备" : "Apply the process with the right equipment"}</h2><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category) => <Link key={category.slug} href={categoryPath(lang, category)} className="group overflow-hidden rounded-3xl border border-neutral-200 bg-[#f5f5f2]"><div className="relative aspect-[4/3] overflow-hidden bg-white"><Image src={category.sceneImage} alt={category.title[lang]} fill sizes="(max-width: 640px) 100vw, 25vw" className="object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-5"><h3 className="font-bold text-neutral-950">{category.title[lang]}</h3><span className="mt-3 inline-block text-sm font-bold text-red-600">{lang === "zh" ? "查看产品" : "View products"} →</span></div></Link>)}</div></div></section>
    <section className="px-4 py-16 sm:px-5 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-black text-neutral-950">{lang === "zh" ? "继续学习" : "Continue learning"}</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{related.map((item,index) => <KnowledgeArticleCard key={item.slug} article={item} lang={lang} index={index} />)}</div></div></section>
  </main>;
}
